<?php

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 */
function drupalgator_install() {
  // Enable some standard blocks.
  $default_theme = 'bootstrap';
  variable_set('theme_default', $default_theme);
  
  // Enable default permissions for system roles.
  user_role_grant_permissions(DRUPAL_ANONYMOUS_RID, array('access content'));
  user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array('access content'));
}